backend:
  name: github
  repo: Anshenoy08/allin1tools
  branch: main
  base_url: https://allin1tools-fud1kolx9-anushenoy08s-projects.vercel.app/

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
